/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-01-18 05:58:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._06bootstrap;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/06bootstrap/include/footer.jsp", Long.valueOf(1705463235696L));
    _jspx_dependants.put("/06bootstrap/include/header.jsp", Long.valueOf(1705557474472L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	String isLogin = "logout";
	if(session.getAttribute("userId")!=null){
		isLogin = "login";
	}	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>GreenBlog</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-md bg-dark navbar-dark\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">GreenBlog</a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("      ");
 
      if(isLogin.equals("logout")) { 
      
      out.write("\r\n");
      out.write("      <a class=\"nav-link\" href=\"login.jsp\">로그인</a>\r\n");
      out.write("      ");
  
      } 
      else {
      
      out.write("\r\n");
      out.write("      <a class=\"nav-link\" href=\"process/logout_process.jsp\">로그아웃</a>\r\n");
      out.write("      ");
	  
      }
      
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"join.jsp\">회원가입</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"boardlist.jsp\">게시글보기</a>\r\n");
      out.write("      </li>    \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>  \r\n");
      out.write("</nav>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	//회원가입시 아이디 중복체크를 해야한다!!!\r\n");
      out.write("	//아이디중복체크를 하지않으면 전송할수 없음\r\n");
      out.write("	//자바스크립트 이벤트 속성 on이벤트=함수명()\r\n");
      out.write("	let isChecking = false;\r\n");
      out.write("	function valid(){\r\n");
      out.write("		if(!isChecking){\r\n");
      out.write("			alert(\"id중복체크를 해주세요\");\r\n");
      out.write("		}\r\n");
      out.write("		return isChecking;\r\n");
      out.write("	}\r\n");
      out.write("	//아이디 중복체크 버튼클릭시 중복체크해죠\r\n");
      out.write("	//userId인풋에 입력한 값이 member테이블에 존재하지 않는지?\r\n");
      out.write("	//ajax\r\n");
      out.write("	function idcheck(){\r\n");
      out.write("		let username = $(\"#userId\").val();\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"POST\", //통신방법 POST\r\n");
      out.write("			url: \"/GreenJsp/member\",      //http://localhost:8090 생략가능\r\n");
      out.write("			data: username,     //보낼데이터\r\n");
      out.write("			contentType: \"text/plain; charset=utf-8\", //보내는 데이터 타입지정\r\n");
      out.write("			dataType: \"text\",   //응답받을데이터 타입 \r\n");
      out.write("			success:function(res){   //통신 성공일경우 success호출됨!!! 콜백으로 들어옴\r\n");
      out.write("				if(res==\"ok\"){\r\n");
      out.write("					isChecking = false;\r\n");
      out.write("					alert(\"유저네임이 중복되었습니다.\");\r\n");
      out.write("				}else {\r\n");
      out.write("					alert(\"유저네임이 중복되지않습니다.\");\r\n");
      out.write("					isChecking = true;\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function(request, textStatus, error){\r\n");
      out.write("				alert(\"통신실패\");\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<div>\r\n");
      out.write("	<h2>회원가입페이지입니다.</h2>\r\n");
      out.write("	<div>\r\n");
      out.write("		<!-- submit이 발생하면 valid()호출 리턴값이 true일때만전송됨 -->\r\n");
      out.write("		<form action=\"process/join_process.jsp\" method=\"post\"\r\n");
      out.write("		onsubmit=\"return valid()\">\r\n");
      out.write("		  <div class=\"form-group\">\r\n");
      out.write("		    아이디\r\n");
      out.write("		    <input type=\"text\" id=\"userId\" class=\"form-control\" \r\n");
      out.write("		    placeholder=\"Enter 아이디\" name=\"userId\" required>\r\n");
      out.write("		    <button type=\"button\" onclick=\"idcheck()\" class=\"btn btn-primary\">아이디중복체크</button>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  <div class=\"form-group\">\r\n");
      out.write("		    비밀번호 \r\n");
      out.write("		    <input type=\"text\" class=\"form-control\" \r\n");
      out.write("		    placeholder=\"Enter 패스워드\" name=\"userPw\" required>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  <div class=\"form-group\">\r\n");
      out.write("		    이름 \r\n");
      out.write("		    <input type=\"text\" class=\"form-control\" \r\n");
      out.write("		    placeholder=\"Enter 이름\" name=\"userName\" required>\r\n");
      out.write("		  </div>\r\n");
      out.write("  		  <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
